### ISSUE TITLE
Something Similar to GSON's @SerializedName

### ISSUE THREAD

**Issue by FireController1847** [falkreon/Jankson#10]
Often times, and especially using a library like this, I'd like to have the name of my variable in the object and the name of the variable in the JSON to be different. In GSON, it'd be like so:

```java
public class MyObject {
  @SerializedName("My Boolean")
  public boolean myBool = false;
}
```

Which would result in a JSON like so:
```json
{
  "My Boolean": false
}
```

It would be really nice to have a feature like this for Jankson.

**Comment by falkreon** [comment]
Fixed by 8ee993b, coming to a release build Soon(tm)!
