### ISSUE TITLE
Parse unquoted strings

### ISSUE THREAD

**Issue by Barteks2x** [falkreon/Jankson#11]
I'm trying to switch from Gson to Jankson, but I know there are some json files being used that contain "comments" in this form:

```json
"comment": "string",
"comment": "more text"
"comment": ~
"comment": "more text"
```

That `~` is exactly as it is in those files, and I want to keep compatibility with them. Gson parses it correctly, interpreting the value as a string. Jankson gives the following error:
```
Found unrecognized token '~' while looking for a json element of any type.
Errored at line 5, column 16
```

**Comment by falkreon** [comment]
Does tilde have a special meaning in Gson? Or is it an unquoted string?

**Comment by Barteks2x** [comment]
It's considered to be an unquoted string. No special meaning there.

**Comment by falkreon** [comment]
This gets into a bit of a parser bind. How should I parse
```json
"comment": ~,
```
is the comma part of the string, or a token delimiter? This is why unquoted strings are not a supported quirk at this time.

**Comment by Barteks2x** [comment]
I'm not sure exactly in what way gson deals with it and why, as I had the impression that it doesn't normally support unquoted strings either. But this worked for some reason and it gets load and print cycle outputs:
```
  "comment": "~",
```
Without this being supported, my best option would be to preprocess those old json files using gson (I can get it to just parse everything and put back into text, without changing order or duplicate keys, just that it's not a few lines of code)

**Comment by falkreon** [comment]
Hmm, looking at https://stackoverflow.com/a/20597916 it may be that Gson just kind of does unquoted strings by accident.

I can just say, "always drop that trailing comma", but then there's sandboxing problems that could potentially destroy the rest of the grammar on the line.

**Comment by Barteks2x** [comment]
Looking at [gson code](https://github.com/google/gson/blob/aa236ec38d39f434c1641aeaef9241aec18affde/gson/src/main/java/com/google/gson/stream/JsonReader.java#L1045-L1068), it looks like it accepts any of the following characters as end of unquoted string:
```java
'/'
'\\
';'
'#'
'=' (only if lenient mode?)
'{'
'}'
'['
']'
':'
','
' '
'\t'
'\f'
'\r'
'\n'
```

**Comment by falkreon** [comment]
I'm trying to minimize my exposure to Gson code, if I wind up doing things the same way as Gson I want it to be because it's the right way to do it, not because copyright infringement :)

But that's potentially workable, rule-wise - a lot of those tokens are clearly for sandboxing reasons. It wouldn't be default behavior, but can certainly be an option in the builder.

**Comment by Barteks2x** [comment]
Since this ended up being about unquoted strings (which I just didn't think of when reporting it initially, even after reading the readme), I think I could live with it if it ends up not supported. (also I didn't think of any potential copyright issues because both projects appear to be open source, under relatively permissive licenses).

**Comment by falkreon** [comment]
Honestly you're right - if I just wanted to lift some code I could just include an extra copyright notice, Apache and MIT are extremely compatible. I'd still rather keep some isolation. There's good cross-pollination like the list of unquoted string delimiters, but lifting code really poisons the possibility for architectural innovation here.

**Comment by falkreon** [comment]
Now that some of the other issues are settled - space being a terminating character here is interesting. I feel like this might not be the "unquoted string" behavior users expect? However, this is almost the same terminating characters for my tokenParserContext, which does unquoted keys. I could just accept tilde to that context, and output value tokens that aren't a special token (like `Infinity` or `false`) as Strings.
