### ISSUE TITLE
Convenience methods for working directly with JsonElement/JsonObject

### ISSUE THREAD

**Issue by Barteks2x** [falkreon/Jankson#17]
Currently working with JsonElement involves a lot of casing between different types (and sometimes instanceof checks) both of which have a bit cumbersome syntax in java.

It would be much easier if there were some builtin methods for getting the needed values directly out of JsonElement.

**Comment by falkreon** [comment]
Even earlier than that, if you have a JsonObject, you can use `obj.get(String.class, "some_string");`, or `someArray.get(MyPOJOClass.class, "elem");`. Once you're at JsonElement, you're stuck downcasting to JsonPrimitive, but once you get there, I've added a bunch of numeric convenience methods to complement `asString`.

**Comment by Barteks2x** [comment]
It's not exactly clear to me how getting them by class works (can I do `obj.get(JsonPrimitive.class, "name")`? or `obj.get(int.class, "name")`?).
My point is that I don't want to work with deserialized objects here, I'm working directly with JsonObject and JsonElement for a reason.

**Comment by falkreon** [comment]
Just like with reflection, you access all primitive types through their boxes: `Integer name = obj.get(Integer.class, "name");`

Kotlin users can use `obj.get(Int.java, "name")` to obtain an `Int?` (optional primitive type).

What I *have* done is put a lot of get-with-default methods into JsonPrimitive, such as `int i = primitive.asInt(defaultValue);` - at release all primitive types will be accessible with minimal reboxing this way. I'm still deciding if it's appropriate to add `obj.getInt(name, defaultValue)` accessors to JsonObject and `arr.getInt(index, defaultValue)` accessors to JsonArray.

**Comment by Barteks2x** [comment]
It would also be nice to have a way to do `asInt` and similar *without* a default, when I actually want to throw an exception if the value is incorrect. While currently not impossible, it's a bit tedious, and I specifically don't want to support magic default values when an entry is missing/invalid.

**Comment by falkreon** [comment]
Then it's best to use the `get(Integer.class, key)` variant, which can return null, giving you your exception as an NPE. You might also be interested in `jankson.fromJsonCarefully` and `marshaller.marshallCarefully` which proactively throw detailed errors about the deserialization process.

**Comment by falkreon** [comment]
Closed by a78e7ca and 2f21423

**Comment by Barteks2x** [comment]
With all of them taking a default value, they really aren't going to be of much use to me anyway, at least not in the way I'm going to use it.
