### ISSUE TITLE
Deserialization into generic list and map fields

### ISSUE THREAD

**Issue by Barteks2x** [falkreon/Jankson#25]
Gson supports it without any issues.

I can create a class like this:
```java
public class SomeClass {
    public List<MyObject> list = new ArrayList<>();
    // other fields
}

public class MyObject {
    // some fields here
}
```
And gson can serialize and deserialize it without any issues. Same for a map. Gson also includes serialization and deserialization of non-primitive keys as an option, which is serialized into something like this:
```json
[
  [ {key json}, {value json} ],
  [ {key json}, {value json} ]
  ...
]
```

The only way to do something like this currently, is to wrap them in a special class and create my own serializers and deserializers (which is what I'm currently doing), but given that it's possible to support it, I think it would be much more convenient if it worked.

**Comment by falkreon** [comment]
That should work, I have unit tests that make sure that works. Check the output from fromJsonCarefully, make sure inner classes are `static`, and make sure you have either an implied no-arg constructor or an explicit one.

**Comment by falkreon** [comment]
That said, if fromJsonCarefully doesn't report the problem with some deserialization configuration, that's a bug.

**Comment by Barteks2x** [comment]
Looks like I did in fact miss the no-args constructor.

**Comment by unascribed** [comment]
Gson does [extremely dirty hacks](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/UnsafeAllocator.java) to instantiate classes it shouldn't be able to. It still baffles me they went to the trouble just to avoid having to tell people to make their inner classes `static`.
