### ISSUE TITLE
Jankson doesn't quote keys with special characters (like ":") when output with unquoted keys is requested

### ISSUE THREAD

**Issue by Barteks2x** [falkreon/Jankson#26]
And then throws a syntax error when trying to load that json.

**Comment by falkreon** [comment]
touche. I made a last-minute check for spaces in keys but didn't think to validate against that. Willfix.

**Comment by Barteks2x** [comment]
Might be a better idea yo just always quote them if they don't match `[a-zA-Z0-9]+`

**Comment by Barteks2x** [comment]
As I just tried to use underscores in keys, I realized that it now unnecessarily quotes underscores

**Comment by falkreon** [comment]
Anything that doesn't match `^[a-zA-Z0-9]+$` gets quoted / is expected to be quoted, exactly as per your suggestion above.
