### ISSUE TITLE
Inconsistency with JsonArray.set and JsonObject.put - set() removes comment, put keeps comments

### ISSUE THREAD

**Issue by Barteks2x** [falkreon/Jankson#27]
I'm not sure which one is the intended behavior here.
`JsonObject.put` replaces the value but keeps comment as is if the key already exists, while `JsonArray.set` creates completely new entry internally, removing existing comment.

This is an unexpected inconsistency in how the library works. If it's intended, I think it should specified in javadocs.

**Comment by falkreon** [comment]
The intended behavior is as in `JsonObject.put`, where comments are unaffected by object mutations. This should become even more pronounced when comment attribution goes away. So this is a bug in `JsonArray.set`
