### ISSUE TITLE
[Feature Request] Introduce toJson for Writers

### ISSUE THREAD

**Issue by Siphalor** [falkreon/Jankson#30]
It would be cool if the `toJson` methods would be able to write their data into Java's `Writer` interface.

This wouldn't just make some code simpler but also make converting giant JSON data more efficient/even possible (I tried it with a really huge Json and it just stopped in the midst of it).

**Comment by falkreon** [comment]
This is a good suggestion. Gonna keep this issue open to remind me.

**Comment by falkreon** [comment]
Writer support is complete with 09797fdc7fddd919251d145f4d0bbfe25863aaa9
