### ISSUE TITLE
Comments null and "" are not considered equal in equals() method

### ISSUE THREAD

**Issue by Barteks2x** [falkreon/Jankson#33]
I was trying to write a unit test for conversion between json data, and I found that `null` and `""` are not considered equal comments, but they result in exactly the same serialized json.

**Comment by falkreon** [comment]
045476e0f1478f8cfe8826bf6fcae59b8972ea06 should have locked this down, but I want to poke it with a few more tests before declaring it Definitely Fixed

**Comment by falkreon** [comment]
Definitely Fixed.
