### ISSUE TITLE
Serialization + deserialization cycle gives differerent results with multiline comments (whitespace)

### ISSUE THREAD

**Issue by Barteks2x** [falkreon/Jankson#35]
Given json object constructed like this:
```java
JsonObject obj = new JsonObject();
JsonPrimitive p = new JsonPrimitive(42);
obj.put("thing", p, "this is a multiline\ncomment");
```
After converting it to string:
```java
String json = (obj.toJson(JsonGrammar.builder().withComments(true).build()));
System.out.println(json);
```
I get the following output:
```json5
{
	/* this is a multiline
	   comment
	*/
	"thing": 42
}
```

Now parsing it back and printing again:
```java
System.out.println(Jankson.builder().build().load(json).toJson(JsonGrammar.builder().withComments(true).build()));
```
I get the following:
```json5
{
	/* this is a multiline
	   	   comment
	*/
	"thing": 42
}
```

The whitespace keeps accumulating each time.

**Comment by falkreon** [comment]
This is likely to be a problem in the "read" part of the cycle, not trimming off clearly-not-part-of-the-comment leading whitespace on the second line. Should be possible to clean that up.

**Comment by Barteks2x** [comment]
This is a minor thing, but is it intended for it to actually strip leading whitespace from comments that are supposed to have it? This can break intentional alignment using spaces or tabs.

**Comment by falkreon** [comment]
I thought about trying to preserve some whitespace, but ultimately I don't see how that can be practically done without passing judgement on how much whitespace the leading indent must be - I could possibly assume a space for the first line and a tab plus three spaces (or 7 spaces) for the second line, but that's a lot more complicated and *still* runs into a problem where it "normalizes" the whitespace on the first run, changing the user's comments in some way.

If I can't avoid normalizing some whitespace, I'd rather apply simpler heuristics that are easier to maintain and easier to explain.

**Comment by Barteks2x** [comment]
Could there be an option to just create multiple single line comments in that case?
