### ISSUE TITLE
Multiline comments sometimes lost in serialization/deserialization cycles

### ISSUE THREAD

**Issue by Barteks2x** [falkreon/Jankson#36]
Json object constructed like this:

```java
JsonObject obj = new JsonObject();
JsonPrimitive p = new JsonPrimitive(42);
obj.put("thing", p, "this is a multiline\ncomment");
```

is then serialized to:
```json5
{ /* this is a multiline */ /* comment */ "thing": 42 }
```
Then deserializing it back into json object keeps only the last line of the comment.

**Comment by falkreon** [comment]
The example you've posted serializes to
```json5
{
	/* this is a multiline
	   comment
	*/
	"thing": 42,
}
```
on the current staging version. I'll run a few more tests to make sure the multi-comment text deserializes correctly, and save those tests in case of regressions in the future.
