### ISSUE TITLE
Jankson 1.2.0-75 stiill doesn't quote keys containing ":" when requesting unquoted keys

### ISSUE THREAD

**Issue by Barteks2x** [falkreon/Jankson#38]
this code:
```java
JsonObject obj = new JsonObject();
obj.put("test:key", JsonNull.INSTANCE);

System.out.println(obj.toJson(JsonGrammar.builder().printUnquotedKeys(true).build()));
```
outputs the following invalid json:
```json5
{
	test:key: null
}
```

**Comment by falkreon** [comment]
Regression of #26 , seems to happen becuase `Pattern.compile("[a-zA-Z0-9]+").asPredicate()` matches "test:key" but not ":", even though it works in regexr, so I'm going to have to reread the Pattern javadocs

**Comment by falkreon** [comment]
This also has a unit test so if it breaks in the future, I'll know
