### ISSUE TITLE
Means to enforce alphabetic sorting of keys when saving

### ISSUE THREAD

**Issue by asiekierka** [falkreon/Jankson#4]
Useful for long lists of keys, such as Charset modules.

**Comment by falkreon** [comment]
Since I've already got ordering guarantees, I can add a flag you can set when creating the Jankson instance.

**Comment by asiekierka** [comment]
I'm not so sure now. I haven't thought of the scenario in which the user rearranges keys themselves, possibly purposefully; that way, they'd get all changes at the bottom...

**Comment by falkreon** [comment]
Going to relegate this issue to the graveyard for now, but it's a possibility in the future if we find a good use-case.
