### ISSUE TITLE
Parameterized types cannot be marshalled.

### ISSUE THREAD

**Issue by kvverti** [falkreon/Jankson#41]
For example, round-tripping `List<Integer>` results in getting a `List<JsonElement>` back.

**Comment by falkreon** [comment]
This is a known bug, but is absolutely on the top of my list of things to fix

**Comment by falkreon** [comment]
Thanks for the report. This has been on my mind for a long time. With 2.0 on the horizon, which was *built* for this, I've done extensive testing with recursive generics. If you have any problems with this in 2.x, please open a new Issue!
