### ISSUE TITLE
Add Automatic-Module-Name to JAR manifest

### ISSUE THREAD

**Issue by Juuxel** [falkreon/Jankson#51]
This would allow requiring Jankson with `module-info`s even if Jankson doesn't ship one itself. (See [this SO answer](https://stackoverflow.com/a/46742802))

**Comment by falkreon** [comment]
Tagging this for 1.2.2 on the java8 branch. I definitely want to play nice with jigsaw everywhere I can. But we should actually go modular for the main branch.
