### ISSUE TITLE
Documentation for the new registerDeserializer method

### ISSUE THREAD

**Issue by eitland** [falkreon/Jankson#55]
After bumping my Jankson package to 1.2.1 it now complains that I should "please use registerDeserializer(Class, Class, DeserializerFunction) instead."

That method however doesn't seem to be dokumented and it alsp doesn't look like there any unit tests for it.

Am I missing something?

**Comment by falkreon** [comment]
`registerDeserializer` is a replacement for `registerTypeAdapter` and `registerPrimitiveTypeAdapter`.

The reason to go to Deserializer is to gain polymorphism; only one typeAdapter can exist for a given target class, whereas a Deserializer can produce the same target class for different source classes.

For example, if you had a primitiveTypeAdapter to unpack JsonPrimitives into Bytes:

`registerPrimitiveTypeAdapter(Byte.class, (it)->(it instanceof Number) ? ((Number)it).byteValue() : null);`

you could instead do something like:
`registerDeserializer(JsonPrimitive.class, Byte.class, (primitive, marshaller)->primitive.asByte(0));`
And now if the source class is a JsonPrimitive and needs to get marshalled to a Byte, it will select this deserializer, but if it's a primitive and needs to be marshalled into a String, it might select a different one.

If you plan on sticking with the 1.2.x branch on Java 8, and you don't need the polymorphism, you can suppress warnings on this as it's not deprecated for removal in this branch. I'm going to do a big documentation push in 1.3+ so hopefully this will be less of a problem going forward.

**Comment by eitland** [comment]
OK, thanks for the answer!

There is still one unanswered question for me: What is this marshaller here?

Sorry if this should be obvious but it isn't for me.

**Comment by falkreon** [comment]
`Marshaller` is an object which is responsible for turning an object of one type into an object of another. Typically that's to/from Json types.

The reason you'd want this in a serializer or deserializer is for compound or nested data. For example, if you ran across a Date object that you wanted as a subkey in your generated JsonElement, you could say `JsonElement dateElem = marshaller.serialize(date);`

Or, in the other direction, `Date date = marshaller.marshall(Date.class, dateElem);`

This requires that there's either a builtin registration in Jankson, a manual registration in the Jankson.Builder, or an appropriate `@Serializer` / `@Deserializer` -annotated method on the object.
