### ISSUE TITLE
fromJson doesn't work properly

### ISSUE THREAD

**Issue by Ansraer** [falkreon/Jankson#6]
Apparently from json doesn't change any values of the newly creazed object. I am currently using the following code:
preset.json:
`{ 
	"name": "Default",
	"version": "1.0.0",
	"description": "An example preset.",
	"authors": [ 
		"Ansraer"
	],
	"rssUpdateFeed": "",
	"folderName": "Default"
}`
Presetinformation
```
public class PresetInformation {
    public String name = "ExamplePreset";
    public String version = "1.0.0";
    public String description = "An example preset.";
    public String authors[] = {"Ansraer"};
    public String rssUpdateFeed = "";
    public String folderName;
}
```
And the following piece of code to load it:
```
JsonObject json = jankson.load(file);
Journeyman.LOGGER.info("json %s", json.toString());
PresetInformation info = jankson.fromJson(json, PresetInformation.class);
 Journeyman.LOGGER.info("Name is %s",info.name);
```
This is what is logged:
```
[01:26:47] [main/INFO]: [JOURNEYMAN]: json { /*  */ "name": "Default", /*  */ "version": "1.0.0", /*  */ "description": "An example preset.", /*  */ "authors": [ "Ansraer" ], /*  */ "rssUpdateFeed": "", /*  */ "folderName": "Default" }
[01:26:47] [main/INFO]: [JOURNEYMAN]: Name is ExamplePreset
```
As you can see the json is loaded correctly from the disk (name is "Default"), but afte turning it into an object the values are reverted to their default values.

**Comment by Ansraer** [comment]
Nevermind, my gradle fucked up. Fixed it by deleting my cache.

**Comment by falkreon** [comment]
I will however want to investigate what is causing that to generate empty comments.
