### ISSUE TITLE
Option to use multiple `//` instead of `/* */` for multi-line comments (when saving)

### ISSUE THREAD

**Issue by LoganDark** [falkreon/Jankson#62]
Would probably have to be parsed as a single comment when loading as well

**Comment by falkreon** [comment]
I would like to fold this improvement into the document system, which has more well-defined comment behavior.

**Comment by falkreon** [comment]
As of 2.0.0, whatever form the comments were loaded in as, will be roundtripped correctly back to the document on save.

The behavior of `@Comment` annotations coming from POJOs will need to be governed by flags on the writer.
