### ISSUE TITLE
Option to use other indentation schemes than '\t'

### ISSUE THREAD

**Issue by lukebemish** [falkreon/Jankson#63]
Currently, the use of `'\t'` for indentation is hardcoded into JsonObject. It would be nice to have an option to configure what is used here (perhaps in JsonGrammar?) to allow for other options, such as 2-space or 4-space indentation.

**Comment by falkreon** [comment]
You're right that this would belong in JsonGrammar, and it would be nice to be able to generate spaces instead of tabs. It could work without too many changes, as long as the indent can be expressed as a CharSequence that's repeatable to represent the effective indent.

**Comment by falkreon** [comment]
I've got the changes in local; gradle's being a jerk due to java versioning, I'll get a commit into main when I have a chance to test it.
