### ISSUE TITLE
parse failure when encountering trailing whitespace

### ISSUE THREAD

**Issue by Inve1951** [falkreon/Jankson#64]
it appears that an exception is thrown when the parser encounters a trailing newline

source: https://github.com/AOCAWOL/BYG/issues/944
call site: https://github.com/AOCAWOL/BYG/blob/079c460419240a9cf3b7b7d68a416216341e41ce/Common/src/main/java/potionstudios/byg/util/jankson/JanksonUtil.java#L114

**Comment by falkreon** [comment]
That's definitely a Jankson bug. Will investigate when I have time.

**Comment by falkreon** [comment]
Finally caught this one by the tail! The 1.2.2 release will contain this fix.
