### ISSUE TITLE
If class doesn't have a default constructor, reading fails silently

### ISSUE THREAD

**Issue by Minenash** [falkreon/Jankson#66]
I had a data class that had a constructor, but I didn't manually add a default constructor, and as a result, when doing `.fromJson(object, class)` it just returns null with no indication of why it was null

**Comment by falkreon** [comment]
have you tried fromJsonCarefully?

**Comment by falkreon** [comment]
Closing as 'half duplicate of #9, half working-as-intended'. Please reopen or get in touch with me on the discord if you have any further questions or need a feature we don't have.
