### ISSUE TITLE
Valid hexadecimal numbers are rejected

### ISSUE THREAD

**Issue by gamma-delta** [falkreon/Jankson#69]
Using Jankson `1.2.1`.

MVE: 

```java
Jankson jankson = Jankson.builder().build;
String src = " { \"foo\": 0xDEADBEEF } ";
JsonObject obj = jankson.load(src);
```

Expected behavior: A json object with `0xdeadbeef` in it.

What happens: A syntax error. `Tried to parse '' as a hexadecimal number, but it appears to be invalid.`

**Comment by falkreon** [comment]
I'm able to reproduce both errors, and a test has been added. This should be fixed shortly.

**Comment by falkreon** [comment]
We're all set! The 1.2.2 release will contain this fix.
