### ISSUE TITLE
Also doesn't accept hexadecimal numbers with leading zeroes

### ISSUE THREAD

**Issue by gamma-delta** [falkreon/Jankson#70]
Using Jankson `1.2.1`.

MVE: 

```java
Jankson jankson = Jankson.builder().build;
String src = " { \"foo\": 0x00FF00 } ";
JsonObject obj = jankson.load(src);
```

Expected behavior: A json object with `0xff00` in it.

What happens: A syntax error. This example throws `Found unexpected character '}' while looking for the colon (':') between a key and a value in an object` but I've also had it throw other things in other examples.

**Comment by falkreon** [comment]
Let's concentrate this discussion in #69 as a hexadecimal number parsing issue.
